### ISSUE TITLE
Firebase setup

### ISSUE THREAD

**Issue by mlentwicklung** [javedahm3d/instagram-clone#2]
Thank you for this nice work! Could you please point me to the Firebase settings in the code? and is there any guide on how to setup the database on Firebase?

**Comment by javedahm3d** [comment]
for this instagram clone , i have enabled firebase authentication , firebase firestore and firebase storage functionalities 

if you to know how to integrate them , in my other repository : https://github.com/javedahm3d/login-using-flutter/tree/email_login
i have tried my best to explain integration of firebase in the readme  at the bottom for different branches 

hope this helps🙂

**Comment by javedahm3d** [comment]
> Thank you for this nice work! Could you please point me to the Firebase settings in the code? and is there any guide on how to setup the database on Firebase?

for this instagram clone , i have enabled firebase authentication , firebase firestore and firebase storage functionalities

if you to know how to integrate them , in my other repository : https://github.com/javedahm3d/login-using-flutter/tree/email_login
i have tried my best to explain integration of firebase in the readme at the bottom for different branches

hope this helps🙂

**Comment by javedahm3d** [comment]
@mlentwicklung 
for this instagram clone , i have enabled firebase authentication , firebase firestore and firebase storage functionalities

if you to know how to integrate them , in my other repository : https://github.com/javedahm3d/login-using-flutter/tree/email_login
i have tried my best to explain integration of firebase in the readme at the bottom for different branches

hope this helps🙂

**Comment by mlentwicklung** [comment]
@javedahm3d Thanks for your response. Now I'm able to use the sign up and I see that the user is added to Firebase Authentication/Users. But no record is added to the database, Firestore/ user. 
So after I sign up in the app I get an exception:

`_CastError (type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast)`
 
on this line:
https://github.com/javedahm3d/instagram-clone-using-flutter-and-firebase/blob/96f82e7286383bdea7fbfbb671bbaa14fa102477/lib/model/user.dart#L25

**Comment by javedahm3d** [comment]
Hey! @mlentwicklung I checked it on my system, its showing no error, maybe you might not have enabled firestore databse in you firebase project, if that's not an issue try to  logout from the the app and register a new user and check 

still pasting my code below :

import 'package:cloud_firestore/cloud_firestore.dart';

class User {
  final String email;
  final String uid;
  final String fullName;
  final String username;
  final String password;
  final List followers;
  final List followings;
  final String photoURL;

  User({
    required this.email,
    required this.uid,
    required this.fullName,
    required this.username,
    required this.password,
    required this.followers,
    required this.followings,
    required this.photoURL,
  });


static User fromSnap(DocumentSnapshot snap) {
    var snapshot = snap.data() as Map<String, dynamic>;

    return User(
      username: snapshot["username"],
      password: snapshot["password"],
      uid: snapshot["uid"],
      email: snapshot["email"],
      photoURL: snapshot["photoURL"],
      fullName: snapshot["fullName"],
      followers: snapshot["followers"],
      followings: snapshot["followings"],
    );
  }

  Map<String, dynamic> toJason() => {
        'email': email,
        'uid': uid,
        'fullName': fullName,
        'username': username,
        'password': password,
        'followers': followers,
        'followings': followings,
        'photoURL': photoURL,
      };
}
